#data_loader.py loads and prepares the scientific papers for summarization 

import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.helpers import clean_text, truncate_text

papers = [
    {"id": "paper_01", "field": "medicine", "title": "Development of mRNA Vaccines and Their Delivery System", "url": "https://pubmed.ncbi.nlm.nih.gov/36697236/", "abstract": "The rapid development of mRNA vaccines contributed to managing the COVID-19 pandemic.", "text": "The rapid development of mRNA vaccines contributed to managing the COVID-19 pandemic and may help manage future outbreaks of infectious diseases. Because the antigens targeted by mRNA vaccines can be easily altered by simply changing the sequence present in the coding region of mRNA structures it is more appropriate to develop vaccines especially during rapidly developing outbreaks. mRNA vaccines have great potential in inducing successful antigen-specific immunity by expressing target antigens in cells and simultaneously triggering immune responses."},
    {"id": "paper_02", "field": "medicine", "title": "SARS-CoV-2 mRNA Vaccines Immunological Mechanism", "url": "https://pubmed.ncbi.nlm.nih.gov/33673048/", "abstract": "A vaccine must elicit efficient adaptive immunity including B and T cell responses.", "text": "To protect against pathogen infection a vaccine must elicit efficient adaptive immunity including B and T cell responses. While B cell responses are key as they can mediate antibody-dependent protection T cells can modulate B cell activity and directly contribute to the elimination of pathogen-infected cells. mRNA vaccines represent a promising platform for infectious disease prevention due to their ability to rapidly encode any antigen of interest and stimulate both humoral and cellular immune responses."},
    {"id": "paper_03", "field": "medicine", "title": "Molecular Mechanisms of Antibiotic Resistance Revisited", "url": "https://pubmed.ncbi.nlm.nih.gov/36411397/", "abstract": "Antibiotic resistance is a global health emergency with resistance detected to all antibiotics in clinical use.", "text": "Antibiotic resistance is a global health emergency with resistance detected to all antibiotics currently in clinical use and only a few novel drugs in the pipeline. Understanding the molecular mechanisms that bacteria use to resist the action of antimicrobials is critical to recognize global patterns of resistance and to improve the use of current drugs as well as for the design of new drugs less susceptible to resistance development."},
    {"id": "paper_04", "field": "medicine", "title": "Global Burden of Bacterial Antimicrobial Resistance in 2019", "url": "https://pubmed.ncbi.nlm.nih.gov/35065702/", "abstract": "Antimicrobial resistance is a major global health threat causing millions of deaths annually.", "text": "Antimicrobial resistance is a major cause of death worldwide with the number of deaths attributable to bacterial antimicrobial resistance being substantial across all world regions. The study estimated the global burden of antimicrobial resistance using predictive statistical modelling to produce estimates for all locations. Resistance to antibiotics was found across a wide range of bacterial pathogens and infection types."},
    {"id": "paper_05", "field": "biology", "title": "CRISPR Technology A Decade of Genome Editing", "url": "https://pubmed.ncbi.nlm.nih.gov/36656942/", "abstract": "CRISPR-Cas9 has transformed biological research and medicine over the past decade.", "text": "CRISPR-Cas9 has become one of the most powerful tools in biology and medicine since its development as a genome editing platform. The technology allows scientists to make precise changes to DNA sequences in virtually any organism. Applications include correcting disease-causing mutations engineering disease-resistant crops developing new model organisms for research and creating potential therapies for genetic diseases."},
    {"id": "paper_06", "field": "biology", "title": "CRISPR Cas9 Gene Editing in Hematological Disorders", "url": "https://pubmed.ncbi.nlm.nih.gov/36610813/", "abstract": "CRISPR Cas9 gene editing shows promise for treating hematological disorders.", "text": "Gene therapy using CRISPR Cas9 has shown promise for treating hematological disorders including sickle cell disease and beta-thalassemia. The approach involves editing hematopoietic stem and progenitor cells to correct disease-causing mutations or to reactivate fetal hemoglobin expression. Clinical trials have demonstrated encouraging results with some patients achieving transfusion independence following treatment."},
    {"id": "paper_07", "field": "medicine", "title": "Memory CD8 T Cell Diversity Following mRNA Vaccination", "url": "https://pubmed.ncbi.nlm.nih.gov/36138186/", "abstract": "High responders to mRNA vaccination showed enhanced antibody neutralizing activity.", "text": "Understanding immune responses to SARS-CoV-2 messenger RNA vaccines is important for improving vaccine design and predicting protection. Analysis of B cell and T cell memory programs showed significant variability between individuals classified as high and low responders. High responders were characterized by enhanced antibody-neutralizing activity increased frequency of central memory T cells and durable spike-specific CD8 T cell responses."},
    {"id": "paper_08", "field": "medicine", "title": "Multidrug-Resistant Bacteria Mechanisms and Prophylaxis", "url": "https://pubmed.ncbi.nlm.nih.gov/36105930/", "abstract": "Multidrug resistance in bacteria has become a critical public health concern.", "text": "Resistance to antibiotics is one of the crucial issues related to public health. Earlier such resistance was limited to nosocomial infections but it has now become a common phenomenon across community settings. Several factors including overexploitation of antibiotics excessive application of broad-spectrum drugs and a shortage of target-oriented antimicrobial drugs contribute to this condition."},
    {"id": "paper_09", "field": "medicine", "title": "mRNA Vaccines Durable Immune Memory to SARS-CoV-2", "url": "https://pubmed.ncbi.nlm.nih.gov/34648302/", "abstract": "mRNA vaccines induce robust and durable cellular immune memory to SARS-CoV-2.", "text": "Recall responses to vaccination in individuals with preexisting immunity primarily increased antibody levels without substantially altering antibody decay rates. These findings demonstrate robust cellular immune memory to SARS-CoV-2 following mRNA vaccination. Both spike-specific CD4 and CD8 T cell responses were detectable months after vaccination and memory B cells continued to mature over time."},
    {"id": "paper_10", "field": "medicine", "title": "Antibiotic Resistance Challenges and Emerging Strategies", "url": "https://pubmed.ncbi.nlm.nih.gov/35949048/", "abstract": "Antibiotic resistance poses a global health threat requiring new antimicrobial strategies.", "text": "Antibiotic resistance has emerged as a major global threat to public health with resistant infections becoming increasingly difficult to treat across all clinical settings. The rise of multidrug-resistant organisms threatens to undermine decades of medical advances. Addressing this challenge requires a multifaceted approach including the development of new antimicrobial agents improved diagnostic tools enhanced infection prevention measures and international coordination on surveillance programs."},
    {"id": "paper_11", "field": "medicine", "title": "Asthma Medications and Management", "url": "https://pubmed.ncbi.nlm.nih.gov/30285350/", "abstract": "Asthma is a chronic inflammatory illness impacting millions daily treated with beta-2 agonists inhaled corticosteroids and other medications.", "text": "Asthma is a wide-reaching chronic inflammatory illness that impacts millions of people daily. It is frequently responsible for unscheduled healthcare usage missed school and workdays. It is an inappropriate immune response to a triggering factor that induces bronchial hyperreactivity constriction with remodeling of smooth muscle and increased mucous secretion into the airways. Several classifications of medications are utilized to treat and manage chronic asthma including beta-2 agonists anticholinergics and inhaled corticosteroids."},
    {"id": "paper_12", "field": "medicine", "title": "Asthma Management in Adults", "url": "https://pubmed.ncbi.nlm.nih.gov/36283607/", "abstract": "Management of asthma in adults has advanced significantly with new biologics improving treatment for severe asthma.", "text": "Management of asthma in adults has advanced in the past 10 years. Central to these advances has been further clarification of type 2 mechanisms of airway inflammation and utilization of biomarkers including eosinophils and fractional exhaled nitric oxide. Five new biologics were approved to revolutionize severe asthma treatment. These biologics
